export const availableSkills: Record<
  string,
  { name: string; iconPath: string }[]
> = {
  "Programming Languages": [
    { name: "C", iconPath: "c/c-original.svg" },
    { name: "C++", iconPath: "cplusplus/cplusplus-original.svg" },
    { name: "C#", iconPath: "csharp/csharp-original.svg" },
    { name: "Go", iconPath: "go/go-original.svg" },
    { name: "Java", iconPath: "java/java-original.svg" },
    { name: "JavaScript", iconPath: "javascript/javascript-original.svg" },
    { name: "TypeScript", iconPath: "typescript/typescript-original.svg" },
    { name: "Python", iconPath: "python/python-original.svg" },
    { name: "Ruby", iconPath: "ruby/ruby-original.svg" },
    { name: "Rust", iconPath: "rust/rust-original.svg" },
    { name: "Kotlin", iconPath: "kotlin/kotlin-original.svg" },
    { name: "Swift", iconPath: "swift/swift-original.svg" },
    { name: "PHP", iconPath: "php/php-original.svg" },
    { name: "Haskell", iconPath: "haskell/haskell-original.svg" },
    { name: "Elixir", iconPath: "elixir/elixir-original.svg" },
    { name: "R", iconPath: "r/r-original.svg" },
    { name: "Dart", iconPath: "dart/dart-original.svg" },
    { name: "Scala", iconPath: "scala/scala-original.svg" },
    { name: "Perl", iconPath: "perl/perl-original.svg" },
    { name: "Lua", iconPath: "lua/lua-original.svg" },
    { name: "Julia", iconPath: "julia/julia-original.svg" },
    { name: "Clojure", iconPath: "clojure/clojure-original.svg" },
    { name: "Groovy", iconPath: "groovy/groovy-original.svg" },
    { name: "Zig", iconPath: "zig/zig-original.svg" },
  ],
  "Scripting & Markup Languages": [
    { name: "Bash", iconPath: "bash/bash-original.svg" },
    { name: "PowerShell", iconPath: "powershell/powershell-original.svg" },
    { name: "CSS", iconPath: "css3/css3-original.svg" },
    { name: "Sass", iconPath: "sass/sass-original.svg" },
    { name: "HTML", iconPath: "html5/html5-original.svg" },
    { name: "Markdown", iconPath: "markdown/markdown-original.svg" },
    { name: "Stylus", iconPath: "stylus/stylus-original.svg" },
  ],
  "Frontend Frameworks & Libraries": [
    { name: "Angular", iconPath: "angularjs/angularjs-original.svg" },
    { name: "React", iconPath: "react/react-original.svg" },
    { name: "Vue.js", iconPath: "vuejs/vuejs-original.svg" },
    { name: "Svelte", iconPath: "svelte/svelte-original.svg" },
    { name: "Next.js", iconPath: "nextjs/nextjs-original.svg" },
    { name: "Nuxt.js", iconPath: "nuxtjs/nuxtjs-original.svg" },
    { name: "Flutter", iconPath: "flutter/flutter-original.svg" }, // Can be used for web/desktop/mobile UI
    { name: "Astro", iconPath: "astro/astro-original.svg" },
    { name: "Bootstrap", iconPath: "bootstrap/bootstrap-original.svg" },
    { name: "Tailwind CSS", iconPath: "tailwindcss/tailwindcss-original.svg" },
    { name: "jQuery", iconPath: "jquery/jquery-original.svg" },
    { name: "Material UI", iconPath: "materialui/materialui-original.svg" },
    { name: "Gatsby", iconPath: "gatsby/gatsby-original.svg" },
    { name: "Ember", iconPath: "ember/ember-original.svg" },
    { name: "Redux", iconPath: "redux/redux-original.svg" },
    { name: "React Router", iconPath: "reactrouter/reactrouter-original.svg" },
  ],
  "Backend Frameworks & Runtimes": [
    { name: "Express", iconPath: "express/express-original.svg" },
    { name: "Node.js", iconPath: "nodejs/nodejs-original.svg" },
    { name: "Bun", iconPath: "bun/bun-original.svg" },
    { name: "GraphQL", iconPath: "graphql/graphql-plain.svg" },
    { name: "Spring", iconPath: "spring/spring-original.svg" },
    { name: "Laravel", iconPath: "laravel/laravel-original.svg" },
    { name: ".NET", iconPath: "dot-net/dot-net-original-wordmark.svg" },
    { name: "Meteor", iconPath: "meteor/meteor-original.svg" }, // Can be full-stack but often leans backend/realtime
  ],
  "Build Tools & Bundlers": [
    { name: "Vite", iconPath: "vitejs/vitejs-original.svg" },
    { name: "Webpack", iconPath: "webpack/webpack-original.svg" },
    { name: "Babel", iconPath: "babel/babel-original.svg" },
    { name: "npm", iconPath: "npm/npm-original-wordmark.svg" },
    { name: "Yarn", iconPath: "yarn/yarn-original.svg" },
  ],
  Databases: [
    { name: "PostgreSQL", iconPath: "postgresql/postgresql-original.svg" },
    { name: "MySQL", iconPath: "mysql/mysql-original.svg" },
    { name: "SQLite", iconPath: "sqlite/sqlite-original.svg" },
    { name: "MongoDB", iconPath: "mongodb/mongodb-original.svg" },
    { name: "Redis", iconPath: "redis/redis-original.svg" },
    { name: "Oracle", iconPath: "oracle/oracle-original.svg" },
    {
      name: "Microsoft SQL Server",
      iconPath: "microsoftsqlserver/microsoftsqlserver-original.svg",
    },
    { name: "MariaDB", iconPath: "mariadb/mariadb-original.svg" },
    {
      name: "DynamoDB",
      iconPath: "dynamodb/dynamodb-original.svg",
    },
    { name: "Cassandra", iconPath: "cassandra/cassandra-original.svg" },
    { name: "Neo4j", iconPath: "neo4j/neo4j-original.svg" },
    { name: "CouchDB", iconPath: "couchdb/couchdb-original.svg" },
    {
      name: "Elasticsearch",
      iconPath: "elasticsearch/elasticsearch-original.svg",
    },
  ],
  "Cloud Platforms & Services": [
    {
      name: "AWS",
      iconPath: "amazonwebservices/amazonwebservices-original-wordmark.svg",
    },
    { name: "Google Cloud", iconPath: "googlecloud/googlecloud-original.svg" },
    { name: "Microsoft Azure", iconPath: "azure/azure-original.svg" },
    { name: "Heroku", iconPath: "heroku/heroku-original.svg" },
    { name: "Vercel", iconPath: "vercel/vercel-original.svg" },
    { name: "Netlify", iconPath: "netlify/netlify-original.svg" },
    {
      name: "Digital Ocean",
      iconPath: "digitalocean/digitalocean-original.svg",
    },
    { name: "Cloudflare", iconPath: "cloudflare/cloudflare-original.svg" },
  ],
  "Backend-as-a-Service (BaaS)": [
    { name: "Appwrite", iconPath: "appwrite/appwrite-original.svg" },

    { name: "Firebase", iconPath: "firebase/firebase-original.svg" },

    { name: "Supabase", iconPath: "supabase/supabase-original.svg" },
  ],
  "DevOps & Infrastructure": [
    { name: "Docker", iconPath: "docker/docker-original.svg" },
    { name: "Kubernetes", iconPath: "kubernetes/kubernetes-original.svg" },
    { name: "Nginx", iconPath: "nginx/nginx-original.svg" },
    { name: "Apache", iconPath: "apache/apache-original.svg" },
    { name: "Jenkins", iconPath: "jenkins/jenkins-original.svg" },
    { name: "Travis CI", iconPath: "travis/travis-plain.svg" },
    { name: "CircleCI", iconPath: "circleci/circleci-plain.svg" },
  ],
  "Version Control & Collaboration": [
    { name: "Git", iconPath: "git/git-original.svg" },
    { name: "GitHub", iconPath: "github/github-original.svg" },
    { name: "GitLab", iconPath: "gitlab/gitlab-original.svg" },
    { name: "Bitbucket", iconPath: "bitbucket/bitbucket-original.svg" },
    { name: "Jira", iconPath: "jira/jira-original.svg" },
  ],
  "Developer Tools & IDEs": [
    { name: "VS Code", iconPath: "vscode/vscode-original.svg" },
    { name: "IntelliJ IDEA", iconPath: "intellij/intellij-original.svg" },
    { name: "WebStorm", iconPath: "webstorm/webstorm-original.svg" },
    { name: "PyCharm", iconPath: "pycharm/pycharm-original.svg" },
    {
      name: "Android Studio",
      iconPath: "androidstudio/androidstudio-original.svg",
    },
    { name: "Xcode", iconPath: "xcode/xcode-original.svg" },
    { name: "Vim", iconPath: "vim/vim-original.svg" },
    { name: "NeoVim", iconPath: "neovim/neovim-original.svg" },
    { name: "Postman", iconPath: "postman/postman-original.svg" },
  ],
  "Testing & Quality Assurance": [
    { name: "Mocha", iconPath: "mocha/mocha-original.svg" },
    { name: "Selenium", iconPath: "selenium/selenium-original.svg" },
    { name: "Puppeteer", iconPath: "puppeteer/puppeteer-original.svg" },
    { name: "Jest", iconPath: "jest/jest-plain.svg" },
    { name: "Cypress", iconPath: "cypressio/cypressio-original.svg" },
  ],
  "Operating Systems": [
    { name: "Linux", iconPath: "linux/linux-original.svg" },
    { name: "Windows", iconPath: "windows8/windows8-original.svg" },
    { name: "macOS", iconPath: "apple/apple-original.svg" },
    { name: "Android", iconPath: "android/android-original.svg" },
  ],
  "Game Development": [
    { name: "Unity", iconPath: "unity/unity-original.svg" },
    {
      name: "Unreal Engine",
      iconPath: "unrealengine/unrealengine-original.svg",
    },
    { name: "Godot", iconPath: "godot/godot-original.svg" },
  ],
  "Data Science & Machine Learning": [
    { name: "TensorFlow", iconPath: "tensorflow/tensorflow-original.svg" },
    { name: "PyTorch", iconPath: "pytorch/pytorch-original.svg" },
    { name: "Pandas", iconPath: "pandas/pandas-original.svg" },
    { name: "NumPy", iconPath: "numpy/numpy-original.svg" },
    { name: "Jupyter", iconPath: "jupyter/jupyter-original.svg" },
    { name: "Anaconda", iconPath: "anaconda/anaconda-original.svg" },
    { name: "Scikit-learn", iconPath: "scikitlearn/scikitlearn-original.svg" },
    { name: "Keras", iconPath: "keras/keras-original.svg" },
  ],
};
