export const availableSkills: Record<
  string,
  { name: string; iconString: string }[]
> = {
  "Programming Languages": [
    { name: "AiScript", iconString: "aiscript" },
    { name: "C", iconString: "c" },
    { name: "C#", iconString: "cs" },
    { name: "C++", iconString: "cpp" },
    { name: "Clojure", iconString: "clojure" },
    { name: "CoffeeScript", iconString: "coffeescript" },
    { name: "Crystal", iconString: "crystal" },
    { name: "Dart", iconString: "dart" },
    { name: "Elixir", iconString: "elixir" },
    { name: "Forth", iconString: "forth" },
    { name: "Fortran", iconString: "fortran" },
    { name: "Go", iconString: "go" },
    { name: "Haskell", iconString: "haskell" },
    { name: "Haxe", iconString: "haxe" },
    { name: "Java", iconString: "java" },
    { name: "JavaScript", iconString: "js" },
    { name: "Kotlin", iconString: "kotlin" },
    { name: "Lua", iconString: "lua" },
    { name: "Nim", iconString: "nim" },
    { name: "OCaml", iconString: "ocaml" },
    { name: "Perl", iconString: "perl" },
    { name: "PHP", iconString: "php" },
    { name: "Python", iconString: "py" },
    { name: "R", iconString: "r" },
    { name: "Ruby", iconString: "ruby" },
    { name: "Rust", iconString: "rust" },
    { name: "Scala", iconString: "scala" },
    { name: "Solidity", iconString: "solidity" },
    { name: "Swift", iconString: "swift" },
    { name: "TypeScript", iconString: "ts" },
    { name: "V", iconString: "v" },
    { name: "Vala", iconString: "vala" },
    { name: "Zig", iconString: "zig" },
  ],
  "Frontend Frameworks & Libraries": [
    { name: "Alpine.js", iconString: "alpinejs" },
    { name: "Angular", iconString: "angular" },
    { name: "Astro", iconString: "astro" },
    { name: "D3.js", iconString: "d3" },
    { name: "Ember", iconString: "ember" },
    { name: "Gatsby", iconString: "gatsby" },
    { name: "HTMX", iconString: "htmx" },
    { name: "jQuery", iconString: "jquery" },
    { name: "Lit", iconString: "lit" },
    { name: "Next.js", iconString: "nextjs" },
    { name: "Nuxt.js", iconString: "nuxtjs" },
    { name: "p5.js", iconString: "p5js" },
    { name: "Pinia", iconString: "pinia" },
    { name: "React", iconString: "react" },
    { name: "Remix", iconString: "remix" },
    { name: "SolidJS", iconString: "solidjs" },
    { name: "Svelte", iconString: "svelte" },
    { name: "Three.js", iconString: "threejs" },
    { name: "Vue.js", iconString: "vue" },
    { name: "Yew", iconString: "yew" },
  ],
  "UI & Styling": [
    { name: "Bootstrap", iconString: "bootstrap" },
    { name: "CSS", iconString: "css" },
    { name: "Emotion", iconString: "emotion" },
    { name: "HTML", iconString: "html" },
    { name: "Less", iconString: "less" },
    { name: "Markdown", iconString: "md" },
    { name: "Material UI", iconString: "materialui" },
    { name: "Pug", iconString: "pug" },
    { name: "Sass", iconString: "sass" },
    { name: "Styled Components", iconString: "styledcomponents" },
    { name: "SVG", iconString: "svg" },
    { name: "Tailwind CSS", iconString: "tailwind" },
    { name: "Vuetify", iconString: "vuetify" },
    { name: "WindiCSS", iconString: "windicss" },
  ],
  "Backend & Server-Side": [
    { name: "Actix", iconString: "actix" },
    { name: "Adonis", iconString: "adonis" },
    { name: "Bun", iconString: "bun" },
    { name: "Deno", iconString: "deno" },
    { name: "Django", iconString: "django" },
    { name: ".NET", iconString: "dotnet" },
    { name: "Elysia", iconString: "elysia" },
    { name: "Express", iconString: "express" },
    { name: "FastAPI", iconString: "fastapi" },
    { name: "Flask", iconString: "flask" },
    { name: "Ktor", iconString: "ktor" },
    { name: "Laravel", iconString: "laravel" },
    { name: "NestJS", iconString: "nestjs" },
    { name: "Node.js", iconString: "nodejs" },
    { name: "Ruby on Rails", iconString: "rails" },
    { name: "Rocket", iconString: "rocket" },
    { name: "Spring", iconString: "spring" },
    { name: "Symfony", iconString: "symfony" },
  ],
  "Databases & Data Storage": [
    { name: "Cassandra", iconString: "cassandra" },
    { name: "DynamoDB", iconString: "dynamodb" },
    { name: "Elasticsearch", iconString: "elasticsearch" },
    { name: "GraphQL", iconString: "graphql" },
    { name: "Hibernate", iconString: "hibernate" },
    { name: "MongoDB", iconString: "mongodb" },
    { name: "MySQL", iconString: "mysql" },
    { name: "PlanetScale", iconString: "planetscale" },
    { name: "PostgreSQL", iconString: "postgres" },
    { name: "Prisma", iconString: "prisma" },
    { name: "Redis", iconString: "redis" },
    { name: "Sequelize", iconString: "sequelize" },
    { name: "SQLite", iconString: "sqlite" },
  ],
  "Cloud, BaaS & Services": [
    { name: "Appwrite", iconString: "appwrite" },
    { name: "AWS", iconString: "aws" },
    { name: "Azul", iconString: "azul" },
    { name: "Azure", iconString: "azure" },
    { name: "Cloudflare", iconString: "cloudflare" },
    { name: "Cloudflare Workers", iconString: "workers" },
    { name: "Firebase", iconString: "firebase" },
    { name: "GCP", iconString: "gcp" },
    { name: "Heroku", iconString: "heroku" },
    { name: "Netlify", iconString: "netlify" },
    { name: "OpenShift", iconString: "openshift" },
    { name: "OpenStack", iconString: "openstack" },
    { name: "Supabase", iconString: "supabase" },
    { name: "Vercel", iconString: "vercel" },
  ],
  "DevOps, CI/CD & Build Tools": [
    { name: "Ansible", iconString: "ansible" },
    { name: "Babel", iconString: "babel" },
    { name: "CMake", iconString: "cmake" },
    { name: "Docker", iconString: "docker" },
    { name: "GitHub Actions", iconString: "githubactions" },
    { name: "Gradle", iconString: "gradle" },
    { name: "Gulp", iconString: "gulp" },
    { name: "Jenkins", iconString: "jenkins" },
    { name: "Kubernetes", iconString: "kubernetes" },
    { name: "Maven", iconString: "maven" },
    { name: "Nginx", iconString: "nginx" },
    { name: "Nix", iconString: "nix" },
    { name: "NPM", iconString: "npm" },
    { name: "PNPM", iconString: "pnpm" },
    { name: "Prometheus", iconString: "prometheus" },
    { name: "Red Hat", iconString: "redhat" },
    { name: "Rollup.js", iconString: "rollupjs" },
    { name: "Sentry", iconString: "sentry" },
    { name: "Terraform", iconString: "terraform" },
    { name: "Vite", iconString: "vite" },
    { name: "Webpack", iconString: "webpack" },
    { name: "Yarn", iconString: "yarn" },
  ],
  "Testing & QA": [
    { name: "Cypress", iconString: "cypress" },
    { name: "Gherkin", iconString: "gherkin" },
    { name: "Jest", iconString: "jest" },
    { name: "Postman", iconString: "postman" },
    { name: "Selenium", iconString: "selenium" },
    { name: "Vitest", iconString: "vitest" },
  ],
  "Version Control": [
    { name: "Bitbucket", iconString: "bitbucket" },
    { name: "Git", iconString: "git" },
    { name: "GitHub", iconString: "github" },
    { name: "GitLab", iconString: "gitlab" },
  ],
  "IDEs & Code Editors": [
    { name: "Android Studio", iconString: "androidstudio" },
    { name: "Atom", iconString: "atom" },
    { name: "CLion", iconString: "clion" },
    { name: "Eclipse", iconString: "eclipse" },
    { name: "Emacs", iconString: "emacs" },
    { name: "IntelliJ IDEA", iconString: "idea" },
    { name: "Neovim", iconString: "neovim" },
    { name: "PhpStorm", iconString: "phpstorm" },
    { name: "PyCharm", iconString: "pycharm" },
    { name: "Replit", iconString: "replit" },
    { name: "Rider", iconString: "rider" },
    { name: "Sublime Text", iconString: "sublime" },
    { name: "Vim", iconString: "vim" },
    { name: "Visual Studio", iconString: "visualstudio" },
    { name: "VS Code", iconString: "vscode" },
    { name: "VSCodium", iconString: "vscodium" },
    { name: "WebStorm", iconString: "webstorm" },
  ],
  "Design & Creative Software": [
    { name: "Ableton", iconString: "ableton" },
    { name: "Adobe After Effects", iconString: "ae" },
    { name: "Adobe Photoshop", iconString: "ps" },
    { name: "Adobe Premiere Pro", iconString: "pr" },
 { name: "Adobe Ilustrator", iconString: "ai" },
    { name: "Adobe XD", iconString: "xd" },
    { name: "Audacity", iconString: "au" },
    { name: "AutoCAD", iconString: "autocad" },
    { name: "Figma", iconString: "figma" },
    { name: "Processing", iconString: "processing" },
    { name: "SketchUp", iconString: "sketchup" },
    { name: "Webflow", iconString: "webflow" },
  ],
  "Game Development": [
    { name: "Bevy", iconString: "bevy" },
    { name: "Blender", iconString: "blender" },
    { name: "GameMaker Studio", iconString: "gamemakerstudio" },
    { name: "Godot", iconString: "godot" },
    { name: "HaxeFlixel", iconString: "haxeflixel" },
    { name: "Roblox Studio", iconString: "robloxstudio" },
    { name: "Tauri", iconString: "tauri" },
    { name: "Unity", iconString: "unity" },
    { name: "Unreal Engine", iconString: "unreal" },
  ],
  "Data Science & AI": [
  
    { name: "Anaconda", iconString: "anaconda" },
    { name: "MATLAB", iconString: "matlab" },
    { name: "GNU Octave", iconString: "octave" },
    { name: "OpenCV", iconString: "opencv" },
    { name: "PyTorch", iconString: "pytorch" },
    { name: "Scikit-learn", iconString: "sklearn" },
    { name: "TensorFlow", iconString: "tensorflow" },
  ],
  "Operating Systems": [
    { name: "Apple", iconString: "apple" },
    { name: "Arch Linux", iconString: "arch" },
    { name: "BSD", iconString: "bsd" },
    { name: "Debian", iconString: "debian" },
    { name: "Kali Linux", iconString: "kali" },
    { name: "Linux", iconString: "linux" },
    { name: "Linux Mint", iconString: "mint" },
    { name: "Plan 9", iconString: "plan9" },
    { name: "Ubuntu", iconString: "ubuntu" },
    { name: "Windows", iconString: "windows" },
  ],
  "Social, Communication & Platforms": [
    { name: "ActivityPub", iconString: "activitypub" },
    { name: "CodePen", iconString: "codepen" },
    { name: "Dev.to", iconString: "devto" },
    { name: "Discord", iconString: "discord" },
    { name: "Discord Bots", iconString: "bots" },
    { name: "Discord.js", iconString: "discordjs" },
    { name: "Fediverse", iconString: "fediverse" },
    { name: "Gmail", iconString: "gmail" },
    { name: "Instagram", iconString: "instagram" },
    { name: "LinkedIn", iconString: "linkedin" },
    { name: "Mastodon", iconString: "mastodon" },
    { name: "Misskey", iconString: "misskey" },
    { name: "Stack Overflow", iconString: "stackoverflow" },
    { name: "Twitter", iconString: "twitter" },
    { name: "WordPress", iconString: "wordpress" },
  ],
  "Productivity & Notes": [
    { name: "Notion", iconString: "notion" },
    { name: "Obsidian", iconString: "obsidian" },
  ],
  "Hardware & Robotics": [
    { name: "Arduino", iconString: "arduino" },
    { name: "Raspberry Pi", iconString: "raspberrypi" },
    { name: "ROS", iconString: "ros" },
  ],
  "Other Technologies": [
    { name: "Bash", iconString: "bash" },
    { name: "Electron", iconString: "electron" },
    { name: "GTK", iconString: "gtk" },
    { name: "IPFS", iconString: "ipfs" },
    { name: "Kafka", iconString: "kafka" },
    { name: "LaTeX", iconString: "latex" },
    { name: "Pkl", iconString: "pkl" },
    { name: "PowerShell", iconString: "powershell" },
    { name: "RabbitMQ", iconString: "rabbitmq" },
    { name: "RxJS", iconString: "reactivex" },
    { name: "Regex", iconString: "regex" },
    { name: "WebAssembly", iconString: "wasm" },
  ],
};
